In [32]:
import numpy as np  

# How to create one dimensional NumPy array?# 

To create python NumPy array use array() function and give items of a list.

In [2]:
import numpy as np # import numpy package
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array


[1 2 3 4]


In [3]:
type(one_d_array)

numpy.ndarray

How to check dimension of NumPy ndarray?
The ndim attribute help to find the dimension of any NumPy array.

In [4]:
one_d_array.ndim # find the dimension of one_d_array

1

How to check the size of the NumPy array?

In [5]:
one_d_array.size

4

 How to check the shape of ndarray?

The shape attribute help to know the shape of NumPy ndarray. It gives output in the form of a tuple data type. Tuple represents the number of rows and columns. Ex: (rows, columns)

In [6]:
two_d_array=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
two_d_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

How to check the shape of ndarray?

The shape attribute help to know the shape of NumPy ndarray. It gives output in the form of a tuple data type. Tuple represents the number of rows and columns. Ex: (rows, columns)

In [8]:
two_d_array.shape   

(2, 4)

How to the data type of NumPy ndarray?

The dtype attribute help to know the data type of ndarray.

In [9]:
one_d_array.dtype



dtype('int32')

In [10]:
two_d_array.dtype

dtype('int32')

# Create metrics using python NumPy functions 

Ones metrics use NumPy ones() function.
np.ones(shape, dtype=None, order=‘C’)

In [11]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Zeros metrics use NumPy zeros() function

In [12]:
a=np.zeros((3, 3), dtype = int)

In [13]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
a.ndim

2

In [15]:
np.zeros((3,3),dtype = bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
np.zeros((3,3),dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

Empty metrics use NumPy empty() function.

 np.empty(shape, dtype=None, order=‘C’)

By default NumPy empty() function give float64 bit random value. According to your requirement change dtype.

In [17]:
np.empty((2,4))      #empty matrix will give any random value

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.02760088e-321, 6.23058707e-307,
        4.45065275e-308]])

Create NumPy 1D array using arange() function

Syntax: np.arange([start,] stop[, step,], dtype=None)

In [18]:
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Create NumPy 1D array using linspace() function

Return evenly spaced numbers over a specified interval.

In [22]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

Convert 1D array to multidimensional array using reshape() function

In [34]:
arr_reshape = np.reshape(arr, (3,4))     #we need to look at the elements it must be even
print(arr_reshape)                        #based on that give a shape of the metrics
                                           #lets say u have 12 elements you can make this combination (3*4)(2*6) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
arr_reshape = np.reshape(arr, (2,6))   #observe the combination
print(arr_reshape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [39]:
arr_reshape = np.reshape(arr, (6,2))   #you need to know the basics of matrices a bit
print(arr_reshape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# 1D to 3D

In [49]:
arr_reshape = np.reshape(arr,(6,2,1))    #look at the order given (6*2*1 = 12)

In [48]:
arr_reshape

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]],

       [[11],
        [12]]])

In [50]:
arr_reshape = np.reshape(arr,(3,2,2))    #look at the order given (3*2*2 = 12)

In [51]:
arr_reshape

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [52]:
oned_twod=np.arange(1,13).reshape(3,4)  #converting one dimension to two dimension

In [53]:
oned_twod

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr_reshape.ndim

3

# Convert multidimensional array in one dimensional

To convert multidimensional array into 1D use ravel() or flatten() function.

In [55]:
arr_reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
arr_reshape.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose

In [57]:
oned_twod.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
one