# Numpy Array Slicing

In [2]:
import numpy as np

In [20]:
mx= np.arange(1,101 ).reshape(10,10) #converting in 2d

In [21]:
mx 

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [14]:
mx[2,1]  #accessing the 0,0 means 0index of the column and the 0 index of the row as a list

22

In [14]:
mx[7,4]   #row first and then coloumn second

75

In [10]:
mx[4,1]

42

In [11]:
#lets check the dimension

In [10]:
mx[0,0].ndim     #here the value is 0 meaning there is no dimension it is a scalar

0

In [11]:
mx[0]      #if we want to acess only row then execute  single row and all colomn

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
mx[0].ndim    #check the dimension it is 1D

1

In [15]:
mx[:,1]     #this is the 1-dimension   This is to access the only column

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [ ]:
#if you want the above column in 2D then lets see down

In [24]:
mx[:, 0:1]   #this is how we access two dimension    :,= all rows grabbed ,0:1= fetches the first column and exclude 1 meaning
                                                    #only one column will be fetched

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [16]:
#let us fetch the two columns
mx[:, 0:2]                         # look at the indexing 

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [18]:
mx[:, 0:2].ndim

2

In [17]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [21]:
mx[0:2,0:2]   #colon is for both rows and colon the first colon is for rows and the second is for the coloum

array([[ 1,  2],
       [11, 12]])

In [26]:
mx[0:2,0:2].ndim 

2

In [27]:
mx[0:,0:3]                       #  All rows and three coloumn

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63],
       [71, 72, 73],
       [81, 82, 83],
       [91, 92, 93]])

In [28]:
mx[:,0:3]                        #same as above 

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63],
       [71, 72, 73],
       [81, 82, 83],
       [91, 92, 93]])

In [30]:
mx[:]                 #entire matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [31]:
mx[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [32]:
mx[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [6]:
mx.itemsize      #this tells you the required size to store the array in the computer it means 4 bytes space

4

In [7]:
mx.dtype             #the data type is integer but it is been stored in the 32bit format  meaning 4 byte

dtype('int32')