# Numpy Mathematica Functions

In [2]:
import numpy as np

In [3]:
#Creating two arrays using np.arange() function and reshape it in 2D using np.reshape() function.

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)           #always note the order of matrices to perform any given operation
 
# print arr1 and arr2
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Addition of Two Numpy Array

In [8]:
#Using + Operator


arr1 + arr2




array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# using np.add() function

In [12]:


np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Subtraction of Two NumPy Array

In [10]:
#Using np.subtract() function


np.subtract(arr1, arr2)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Division of Two NumPy Array

In [13]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Multiplication of Two NumPy Array

In [15]:
arr1 * arr2                  #element wise multiplication

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# Matrix Product of Two NumPy Array (matrix)

In [4]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr1 @ arr2                       #firstRow into first column

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [18]:
arr1.dot(arr2)      #matrix product using dot 


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# NumPy Mathematical Built-in functions

np.max()  To find maximum value from an array.

In [19]:
arr1.max()

9

In [6]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr1.max(axis = 0) # return max value from each column

array([7, 8, 9])

In [7]:
arr1.max(axis = 1) # return max value from each row

array([3, 6, 9])

np.argmax() 

In [22]:
arr1.argmax() # return index of max value of an array


8

np.min()

To find minimum value from an array.

In [23]:
arr1.min()

1

In [24]:
arr1.min(axis = 0) # return min value from each column

array([1, 2, 3])

In [25]:
arr1.argmin() # return index of min value of an array

0

np.sum()  Return sumation of NuPy array.

In [26]:
np.sum(arr1)

45

In [27]:
np.sum(arr1, axis = 0) # return sum of each column

array([12, 15, 18])

In [28]:
np.sum(arr1, axis = 1) # return sum of each row


array([ 6, 15, 24])

# np.mean()

Return mean of NumPy array.

In [29]:
np.mean(arr1)

5.0

# np.sqrt()

Return square root of each element of NumPy array.

In [30]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# np.std()



Return standerd division of Numpy array.

In [31]:
np.std(arr1)

2.581988897471611

# no.exp()

Return exponential value of each element of the NumPy array.

In [8]:
np.exp(arr1)   #e to the power x

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# no.log()

Return natural log of each element of NumPy array.

In [34]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

# np.log10()

Return log to the base 10 value of each element of NumPy array.

In [35]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])