In [12]:
import numpy as np

In [13]:
arr1=np.arange(1,17).reshape(4,4)   #creating 4cross 4 array

In [14]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [15]:
arr2=np.arange(17,33).reshape(4,4) 

In [16]:
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [17]:
arr2.ndim

2

# let us concatenate the array by column to column

In [18]:
list1=[2,3,4]    #how do u do it in the list

In [19]:
list2=[5,6,7]

In [20]:
list1+list2

[2, 3, 4, 5, 6, 7]

In [21]:
list3 = list1+list2

In [22]:
list3

[2, 3, 4, 5, 6, 7]

In [23]:
arr1+arr2         #this is addition but not the concatenation

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [16]:
arr_concatenate=np.concatenate((arr1,arr2))   #column wise concatenation

In [17]:
arr_concatenate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [18]:
arr_concatenate.ndim

2

In [20]:
arr_concatenate.shape

(8, 4)

# Row wise concatenation of array

In [24]:
np.concatenate((arr1,arr2),axis= 1)     #by default the axis is "0" for concatenation which will take as column for "0"

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [25]:
np.vstack((arr1,arr2))    #alternate methods for concatenations column wise

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [26]:
np.hstack((arr1,arr2))     #alternate method for concatenation row wise

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [29]:
np.hstack((arr1,arr2,arr1))    #multiple array concatenation

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

# split function

split or breaking array

In [27]:
np.split(arr1,2,axis=0)      #give values as how many parts we need of that array 

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

The above got splitted in two array by two rows each time

In [28]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
np.split(arr1,3,axis=0)      #no correct sizes  here it is 3

ValueError: array split does not result in an equal division

In [33]:
np.split(arr1,2,axis=1)    #axis=1 will give you the split column wise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [34]:
mx = np.split(arr1,2)    

In [35]:
type(mx)         #hence when split happens this become a list

list

In [36]:
mx[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
type(mx[0])    #we get array hence it split the array and store into a list

numpy.ndarray

In [43]:
np.split(arr1,2,axis = 1)   #splits array column wise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [41]:
np.split(arr1,3,axis = 1)            #we need to give such a value which splits into exact row splits

ValueError: array split does not result in an equal division

In [44]:
 #using split function one 1D array

In [48]:
d1=np.array([4,7,1,3,9])    

In [49]:
#lets us split  the 1D array in multiple array

In [50]:
np.split(d1)

TypeError: split() missing 1 required positional argument: 'indices_or_sections'

In [55]:
np.split(d1,[2,3,5])    #this is little tricky after d1 i am giving the positions of values which will be the next array

[array([4, 7]), array([1]), array([3, 9]), array([], dtype=int32)]

In [57]:
np.split(d1,[1,2,3])    #here observe 1=first value in d1,2= second value,3= third and remainnig assigned to the next array

[array([4]), array([7]), array([1]), array([3, 9])]